#!/bin/bash -e

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

main() {
    get_sources
    docker build -t lfs8 .
}

get_sources() {
    cd "$script_dir"
    if [[ -e sources ]]; then
        return
    fi
    mkdir -p sources
    wget --input-file="res/wget-list" --continue --directory-prefix="sources"
    pushd sources
    md5sum -c ../res/md5sums || die bad sources
    popd
}

main
