#!/bin/bash -e

apt-get -q update
apt-get -q -y install build-essential bison gawk texinfo wget file
apt-get -q -y autoremove
rm -rf /var/lib/apt/lists/*
rm -f /bin/sh
cd /bin
ln -s bash sh
mkdir -p /src "$LFS"
chmod 777 /tmp
