#!/bin/bash -e

mkdir -pv "$LFS/sources"
chmod -v a+wt "$LFS/sources"
mkdir -pv "$LFS/tools"
ln -sv "$LFS/tools" /

# Create user and group.
groupadd lfs
useradd -s /bin/bash -g lfs -m -k /dev/null lfs

# Set user password.
echo lfs:lfs | chpasswd

chown -v lfs "$LFS/tools" "$LFS/sources"
chown lfs /src
