#!/bin/bash -e

tar -xf "$LFS"/sources/expect*.tar.gz -C /tmp/
cd /tmp/expect*

cp -v configure{,.orig}
sed 's:/usr/local/bin:/bin:' configure.orig > configure

./configure \
    --prefix=/tools \
    --with-tcl=/tools/lib \
    --with-tclinclude=/tools/include

make

make SCRIPTS="" install

rm -rf /tmp/*
