#!/bin/bash -e

tar -xf "$LFS"/sources/ncurses-*.tar.gz -C /tmp/
cd /tmp/ncurses-*

sed -i s/mawk// configure

./configure \
    --prefix=/tools \
    --with-shared \
    --without-debug \
    --without-ada \
    --enable-widec \
    --enable-overwrite

make
make install

rm -rf /tmp/*
