#!/bin/bash -e

tar -xf "$LFS"/sources/coreutils-* -C /tmp/
cd /tmp/coreutils-*

echo '--- configure-orig      2017-06-13 22:13:24.190630857 +0100
+++ configure   2017-06-13 22:17:58.459464165 +0100
@@ -32195,7 +32195,7 @@
 
   gl_abort_bug=no
   case "'"\$"'host_os" in
-    mingw*)
+    *)
       gl_cv_func_getcwd_path_max=yes
       ;;
     *)
' | patch configure
./configure --prefix=/tools --enable-install-program=hostname
make
make install

rm -rf /tmp/*
