#!/bin/bash -e

tar -xf "$LFS"/sources/tar-* -C /tmp/
cd /tmp/tar-*

echo '--- configure-orig      2017-06-14 20:36:58.289141312 +0100
+++ configure   2017-06-14 20:37:01.781155547 +0100
@@ -20697,7 +20697,7 @@
 
   gl_abort_bug=no
   case "'"\$"'host_os" in
-    mingw*)
+    *)
       gl_cv_func_getcwd_path_max=yes
       ;;
     *)
' | patch configure
./configure --prefix=/tools
make
make install

rm -rf /tmp/*
