#!/bin/bash -e

tar -xf "$LFS"/sources/binutils-*.tar.bz2 -C /tmp/
cd /tmp/binutils-*
mkdir -v build
cd build

CC="$LFS_TGT"-gcc AR="$LFS_TGT"-ar RANLIB="$LFS_TGT"-ranlib ../configure \
    --prefix=/tools \
    --disable-nls \
    --disable-werror \
    --with-lib-path=/tools/lib \
    --with-sysroot

make
make install
make -C ld clean
make -C ld LIB_PATH=/usr/lib:/lib
cp -v ld/ld-new /tools/bin
rm -rf /tmp/*
