#!/bin/bash -e

tar -xf "$LFS"/sources/binutils-2.27.tar.bz2 -C /tmp/
pushd /tmp/binutils-2.27
mkdir -v build
cd build
../configure \
    --prefix=/tools \
    --with-sysroot="$LFS" \
    --with-lib-path=/tools/lib \
    --target="$LFS_TGT" \
    --disable-nls \
    --disable-werror
make
mkdir -pv /tools/lib
ln -sv lib /tools/lib64
make install
popd
rm -rf /tmp/*
