#!/bin/bash -e

tar -xf "$LFS"/sources/gcc-*.tar.bz2 -C /tmp/

cd /tmp/gcc-*

cat gcc/limitx.h gcc/glimits.h gcc/limity.h > \
	"$(dirname "$("$LFS_TGT"-gcc -print-libgcc-file-name)")"/include-fixed/limits.h

for file in gcc/config/{linux,i386/linux{,64}}.h; do
    cp -uv "$file"{,.orig}
    sed -e 's@/lib\(64\)\?\(32\)\?/ld@/tools&@g' \
        -e 's@/usr@/tools@g' "$file".orig > "$file"
    echo '
#undef STANDARD_STARTFILE_PREFIX_1
#undef STANDARD_STARTFILE_PREFIX_2
#define STANDARD_STARTFILE_PREFIX_1 "/tools/lib/"
#define STANDARD_STARTFILE_PREFIX_2 ""' >> "$file"
    touch "$file".orig
done

tar -xf "$LFS"/sources/mpfr-*.tar.xz
mv -v mpfr-* mpfr

tar -xf "$LFS"/sources/gmp-*.tar.xz
mv -v gmp-* gmp

tar -xf "$LFS"/sources/mpc-*.tar.gz
mv -v mpc-* mpc

mkdir -v build
cd build

CC="$LFS_TGT"-gcc \
CXX="$LFS_TGT"-g++ \
AR="$LFS_TGT"-ar \
RANLIB="$LFS_TGT"-ranlib \
../configure \
    --prefix=/tools \
    --with-local-prefix=/tools \
    --with-native-system-header-dir=/tools/include \
    --enable-languages=c,c++ \
    --disable-libstdcxx-pch \
    --disable-multilib \
    --disable-bootstrap \
    --disable-libgomp

make
make install
ln -sv gcc /tools/bin/cc

rm -rf /tmp/*
